### ISSUE TITLE
работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [ChewedUpCake/test1#1]
1)
фон не соответствует макету
![image](https://user-images.githubusercontent.com/8464662/105643808-bd5e9900-5e9a-11eb-9c85-dea348231824.png)

2)
цвет не соответствует макету
![image](https://user-images.githubusercontent.com/8464662/105643821-d8310d80-5e9a-11eb-85b7-38f78c45504e.png)

3)
результат в фокусе не соответсвует макету
![image](https://user-images.githubusercontent.com/8464662/105643831-e41ccf80-5e9a-11eb-8a4e-e2c9d21947de.png)

4)
непраивльная ширина
![image](https://user-images.githubusercontent.com/8464662/105643845-fdbe1700-5e9a-11eb-8a1d-83c148df0ba0.png)

5)
требования к размеру шрифта для всех разрешенией -не выполнены
![image](https://user-images.githubusercontent.com/8464662/105643856-10d0e700-5e9b-11eb-9238-f6bc5b4c3647.png)

6)
размер шрифта не соответствует задаче
![image](https://user-images.githubusercontent.com/8464662/105643878-31993c80-5e9b-11eb-8ae4-87b1087aa4c8.png)

7)
форма не соответствует задаче
![image](https://user-images.githubusercontent.com/8464662/105643889-45dd3980-5e9b-11eb-9bde-afee4ac4db34.png)

8)
заголовок не соответствует задаче
![image](https://user-images.githubusercontent.com/8464662/105643897-54c3ec00-5e9b-11eb-9897-ba8695384fba.png)

9)
сетка не соответствует задаче
![image](https://user-images.githubusercontent.com/8464662/105643916-6ad1ac80-5e9b-11eb-90ac-c5d9116223e1.png)

10)
код невалиден
![image](https://user-images.githubusercontent.com/8464662/105643926-7c1ab900-5e9b-11eb-9612-5b52a47e9c13.png)

**Comment by ChewedUpCake** [comment]
Провёл работу над ошибками!)

**Comment by Alecto** [comment]
3 - не исправлено

**Comment by ChewedUpCake** [comment]
> 3 - не исправлено

Исправил ошибку
